'use client';

import React, { useEffect, useState } from 'react';
import './globals.css'
// import { Inter } from 'next/font/google'

import Image from 'next/image';
import loadingGif from '../images/loading.gif'
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  let [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(false);
  }, []);


  console.log(loading);

  return (
    <html lang="en">
      <body> {loading==false ? children : <Image style={{margin:'14vh 25%',width:'50%',height:'auto'}} src={loadingGif}/>}</body>
    </html>
  )
}
